const MOVIEDETAILDATA = [
    {
        id: 0,
        title: "His Girl Friday",
        year: "1940",
        longDescription: "When hard-charging New York newspaper editor Walter Burns (Cary Grant) discovers that his ex-wife, investigative reporter Hildy Johnson (Rosalind Russell), has gotten engaged to milquetoast insurance agent Bruce Baldwin (Ralph Bellamy), he unsuccessfully tries to lure her away from tame domestic life with a story about the impending execution of convicted murderer Earl Williams. But when Hildy discovers Williams may be innocent, her reporter instincts take over.",
        movieImg: "/assets/hisGirlFriday.jpeg",
        movieAlt: "His Girl Friday Poster",
        director: "Howard Hawks",
        writers: "Charles Lederer, Ben Hecht, Charles MacArthur",
        cast: "Cary Grant, Rosalind Russell, Ralph Bellamy, Gene Lockhart",
        producer: "Howard Hawks",
        cinematographer: "Joseph Walker",
        editor: "Gene Havlick",
        artDirector: "Lionel Banks",
        videoUrl: "/assets/videos/HisGirlFriday.mp4",
        videoAlt: "His Girl Friday Film"

    },
    {
        id: 1,
        title: "House on Haunted Hill",
        year: "1959",
        longDescription: "Rich oddball Frederick Loren (Vincent Price) has a proposal for five guests at a possibly haunted mansion: Show up, survive a night filled with scares and receive $10,000 each. The guest of honor is Loren's estranged wife, Annabelle (Carol Ohmart), who, with her secret lover, Dr. Trent (Alan Marshal), has concocted her own scheme to scare Loren's associate, Nora Manning (Carolyn Craig), into shooting the potentially crazy millionaire. But more spooks and shocks throw a wrench into the plan.",
        movieImg: "/assets/HouseOnHauntedHill.jpg",
        movieAlt: "House On Haunted Hill Movie Poster",
        director: "William Castle",
        writers: "Robb White",
        cast: "Vincent Price, Carol Ohmart, Richard Long",
        producer: "William Castle, Robb White",
        cinematographer: "Carl E. Guthrie",
        editor: "Roy V. Livingston",
        artDirector: "Dave Milton",
        videoUrl: "/assets/videos/HouseOnHauntedHill.mp4",
        videoAlt: ""

    },
    {
        id: 2,
        title: "Last Woman on Earth",
        year: "1960",
        longDescription: "A gangster (Anthony Carbone), his wife (Betsy Jones-Moreland) and a lawyer (Edward Wain) have Earth to themselves.",
        movieImg: "/assets/TheLastWomanOnEarth.jpg",
        movieAlt: "Last Woman on Earth Movie Poster",
        director: "Roger Corman",
        writers: "Robert Towne",
        cast: "Betsy Jones-Moreland, Antony Carbone, Edward Waine",
        producer: "Roger Corman, Charles Hannawait",
        cinematographer: "Jacques R. Marquette",
        editor: "Anthony Carras",
        artDirector: "Stanley Watson",
        videoUrl: "/assets/videos/LastWomenOnEarth.mp4",
        videoAlt: "Last Woman on Earth Film"

    },
    {
        id: 3,
        title: "My Man Godfrey",
        year: "1936",
        longDescription: "The new family butler (David Niven) of a Park Avenue socialite (June Allyson) is an Austrian diplomat incognito. ",
        movieImg: "/assets/MyManGodfrey.jpg",
        movieAlt: "My Man Godfrey Movie Poster",
        director: "Gregory La Cava",
        writers: "Morrie Ryskind, Eric Hatch, Zoe Atkins, Gregory La Cava, Robert Presnell Sr.",
        cast: "William Powell, Carole Lombard, Alice Brady",
        producer: "Charles R. Rogers",
        cinematographer: "Ted Tetzlaff",
        editor: "Ted J. Kent, Russel F. Schoengarth",
        artDirector: "Charles D. Hall",
        videoUrl: "/assets/videos/MyManGodfrey.mp4",
        videoAlt: "My Man Godfrey Film"

    },
    {
        id: 4,
        title: "Night of the Living Dead",
        year: "1968",
        longDescription: "Night of the Living Dead - A disparate group of individuals takes refuge in an abandoned house when corpses begin to leave the graveyard in search of fresh human bodies to devour. The pragmatic Ben (Duane Jones) does his best to control the situation, but when the reanimated bodies surround the house, the other survivors begin to panic. As any semblance of order within the group begins to dissipate, the zombies start to find ways inside -- and one by one, the living humans become the prey of the deceased ones.",
        movieImg: "/assets/NOTLD.jpg",
        movieAlt: "Night of the Living Dead Movie Poster",
        director: "George A. Romero",
        writers: "John A. Russo, George A. Romero",
        cast: "Duane Jones, Judith O'Dea, Karl Hardman, Marilyn Eastman",
        producer: "Karl Hardman, Russell Streiner",
        cinematographer: "George A. Romero",
        editor: "George A. Romero",
        artDirector: "Charles O'Data",
        videoUrl: "/assets/videos/NightOfTheLivingDead.mp4",
        videoAlt: "Night of the Living Dead Film"

    },
    {
        id: 5,
        title: "The Phantom of the Opera",
        year: "1925",
        longDescription: "In this silent horror classic, aspiring young opera singer Christine Daaé (Mary Philbin) discovers that she has a mysterious admirer intent on helping her become a lead performer. This enigmatic masked presence is Erik, also known as the Phantom (Lon Chaney), a horribly disfigured recluse who lives underneath the Paris Opera House. When the Phantom takes Christine prisoner and demands her devotion and affection, her suitor, Vicomte Raoul de Chagny (Norman Kerry), sets out to rescue her.",
        movieImg: "/assets/ThePhantomOfTheOpera.jpg",
        movieAlt: "The Phantom of the Opera Movie Poster",
        director: "Rupert Julian, Lon Chaney, Ernst Laemmle, Edward Sedgwick",
        writers: "Gaston Leroux",
        cast: "Lon Chaney, Mary Philbin, Norman Kerry",
        producer: "Carl Laemmle",
        cinematographer: "Milton Bridenbecker, Virgil Miller, Charles Van Enger",
        editor: "Edward Curtiss, Maurice Pivar, Gilmore Walker",
        artDirector: "Charles D. Hall, Elmer Sheeley",
        videoUrl: "/assets/videos/ThePhantomOfTheOpera.mp4",
        videoAlt: "The Phantom of the Opera Film"

    },
    {
        id: 6,
        title: "The Adventurer",
        year: "1917",
        longDescription: "The Tramp breaks out of prison, saves a girl and her mother from drowning, and wrecks a swank party.",
        movieImg: "/assets/TheAdventurer.jpg",
        movieAlt: "The Adventurer Movie Poster",
        director: "Charlie Chaplain",
        writers: "Vincent Bryan, Charles Chaplin, Maverick Terrell",
        cast: "Charlie Chaplain, Edna Purviance, Eric Campbell",
        producer: "Henry P. Caulfield, Charles Chaplin, John Jasper",
        cinematographer: "William C. Foster, Roland Totheroh",
        editor: "Charles Chaplin",
        artDirector: "George Cleethrope",
        videoUrl: "/assets/videos/TheAdventurer.mp4",
        videoAlt: "The Adventurer Film"

    },
    {
        id: 7,
        title: "The Brain that Wouldn't Die",
        year: "1962",
        longDescription: "Dr. Bill Cortner (Jason Evers) and his fiancée, Jan Compton (Virginia Leith), are driving to his lab when they get into a horrible car accident. Compton is decapitated. But Cortner is not fazed by this seemingly insurmountable hurdle. His expertise is in transplants, and he is excited to perform the first head transplant. Keeping Compton's head alive in his lab, Cortner plans the groundbreaking yet unorthodox surgery. First, however, he needs a body.",
        movieImg: "/assets/TBTWD.jpg",
        movieAlt: "The Brain that Wouldn't Die Movie Poster",
        director: "Joseph Green",
        writers: "Joseph Green, Rex Carlton",
        cast: "Jason Evers, Virginia Leith, Anthony La Penna",
        producer: "Rex Carlton, Mort Landberg",
        cinematographer: "Stephen Hajnal",
        editor: "Marc Anderson",
        artDirector: "Paul Fanning",
        videoUrl: "/assets/videos/TheBrainThatWouldNotDie1962.mp4",
        videoAlt: "The Brain that Wouldn't Die Film"

    },
    {
        id: 8,
        title: "The Hitch Hiker",
        year: "1953",
        longDescription: "Ray (Edmond O'Brien) and Gilbert's (Frank Lovejoy) fishing trip takes a terrifying turn when the hitchhiker (William Talman) they pick up turns out to be a sociopath on the run from the law. He's killed before, and he lets the two know that as soon as they're no longer useful, he'll kill again. The two friends plot an escape, but the hitchhiker's peculiar physical affliction, an eye that never closes even when he sleeps, make it impossible for them to tell when they can make a break for it.",
        movieImg: "/assets/TheHitchHiker.jpg",
        movieAlt: "The Hitch Hiker Movie Poster",
        director: "Ida Lupino",
        writers: "Collier Young, Ida Lupino, Robert L. Joseph",
        cast: "Edmond O-Brien, Frank Lovejoy, William Talman",
        producer: "Christian Nyby, Collier Young",
        cinematographer: "Nicholas Musuraca",
        editor: "Douglas Stewart",
        artDirector: "Albert S. D'Agostino, Walter E. Keller",
        videoUrl: "/assets/videos/TheHitchHiker.mp4",
        videoAlt: "The Hitch Hiker Film"

    },
    {
        id: 9,
        title: "The Lost World",
        year: "1925",
        longDescription: "In London, professor Challenger (Wallace Beery) announces that prehistoric creatures are alive and flourishing in the Amazon jungle and declares his intention to mount an expedition proving his point. Journalist Edward Malone (Lloyd Hughes) volunteers to go and convinces his newspaper to fund the journey. Paula White (Bessie Love) hopes to find her father, a missing explorer. They and others undertake the voyage and witness dinosaurs and humanoids doing battle in a magnificent landscape.",
        movieImg: "/assets/TheLostWorld.jpg",
        movieAlt: "The Lost World Movie Poster",
        director: "Harry O. Hoyt",
        writers: "Marion Fairfax, Arthur Conan Doyle",
        cast: "William Berry, Bessie Love, Lloyd Hughes",
        producer: "Scott MacQueen, R.J. Miller, Cecil Copping",
        cinematographer: "Arthur Edeson",
        editor: "George McGuire",
        artDirector: "Milton Menasco",
        videoUrl: "/assets/videos/LostWorld.mp4",
        videoAlt: "The Lost World Film"

    },
    {
        id: 10,
        title: "Voyage to the Planet of Pre-historic women",
        year: "1968",
        longDescription: "Astronauts encounter monsters and beautiful women after their spaceship crashes on Venus.",
        movieImg: "/assets/voyageToThePlanet.jpg",
        movieAlt: "Voyage to the Planet of Pre-historic Women Movie Poster",
        director: "Peter Bogdanovich (as Derek Thomas)",
        writers: "Henry Ney",
        cast: "Mamie Van Doren, Mary Marr, Paige Lee",
        producer: "Norman D. Wells, Roger Corman",
        cinematographer: "Flemming Olsen, Arkadi Klimov",
        editor: "Bob Collins",
        artDirector: "Vittorio Ferroni",
        videoUrl: "/assets/videos/VoyageToThePlanetofPrehistoricWomen.mp4",
        videoAlt: "Voyage to the Planet of Pre-historic Women Film"

    }

];

export default MOVIEDETAILDATA;