export const GET_FILMS = "GET_FILMS";
export const FILMS_LOADING = "FILMS_LOADING";
export const FILMS_ERROR = "FILMS_ERROR";

export const GET_COMMENTS = "GET_COMMENTS";
export const COMMENTS_LOADING = "COMMENTS_LOADING";
export const COMMENTS_ERROR = "COMMENTS_ERROR";
export const ADD_COMMENT = "ADD_COMMENT";

export const GET_EVENTS = "GET_EVENTS";
export const EVENTS_LOADING = "EVENTS_LOADING";
export const EVENTS_ERROR = "EVENTS_ERROR";

export const ADD_WATCHLIST = "ADD_WATCHLIST";
export const DELETE_WATCHLIST = "DELETE_WATCHLIST";

export const GET_LIKES = "GET_LIKES";
export const GET_LIKES_FAILED = "GET_LIKES_FAILED";

export const GET_REVIEWS = "GET_REVIEWS";
export const REVIEWS_LOADING = "REVIEWS_LOADING";
export const REVIEWS_ERROR = "REVIEWS_ERROR";
export const ADD_REVIEWS = "ADD_REVIEWS";

export const POST_CONTACT = "POST_CONTACT";
