export const GET_FILMS = "GET_FILMS";
export const FILMS_LOADING = "FILMS_LOADING";
export const FILMS_ERROR = "FILMS_ERROR";

export const GET_FILM_DETAILS = "GET_FILM_DETAILS";
export const FILMS_DETAILS_LOADING = "FILMS_DETAILS_LOADING";
export const FILMS_DETAILS_ERROR = "FILMS_DETAILS_ERROR";

export const GET_COMMENTS = "GET_COMMENTS";
export const COMMENTS_LOADING = "COMMENTS_LOADING";
export const COMMENTS_ERROR = "COMMENTS_ERROR";
export const ADD_COMMENT = "ADD_COMMENT";

export const GET_EVENTS = "GET_EVENTS";
export const EVENTS_LOADING = "EVENTS_LOADING";
export const EVENTS_ERROR = "EVENTS_ERROR";

export const ADD_WATCHLIST = "ADD_WATCHLIST";
export const DELETE_WATCHLIST = "DELETE_WATCHLIST";

export const ADD_LIKE = "ADD_LIKE";
export const DELETE_LIKE = "DELETE_LIKE";